DjangoApp/urls.py
"""
Definition of urls for DjangoApp.
"""

from datetime import datetime
from django.conf.urls import url
from app.forms import BootstrapAuthenticationForm
from app.views import *
from app.models import *
from django.contrib.auth.views import *

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
    url(r'^$', home, name='home'),
    url(r'^figures', figures, name='figures'),
    url(r'^contact', contact, name='contact'),
    url(r'^papers', papers, name='papers'),
    url(r'^login/$', login, {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$', logout, {  'next_page': '/'  },        name='logout')

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

app/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
        url(r'^$', views.post_list, name='post_list'),
        url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
]

app/models.py
"""
Definition of models.
"""

from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    photo = models.ImageField(upload_to='static/photos/%Y/%m/%d', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

app/views.py
"""
Definition of views.
"""
import json
import os

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from django.conf import settings
from django.http import Http404
from django.template import Template, Context
from django.template.loader_tags import BlockNode
from django.utils._os import safe_join
from django.views.generic import ListView, DetailView
from .models import Post


def get_page_or_404(name):
    """Return page content as a Django template or raise 404 error."""
    try:
        file_path = safe_join(settings.SITE_PAGES_DIRECTORY, name)
    except ValueError:
        raise Http404('Page Not Found')
    else:
        if not os.path.exists(file_path):
            raise Http404('Page Not Found')
   
    with open(file_path, 'r') as f:
        page = Template(f.read())
    meta = None
    for i, node in enumerate(list(page.nodelist)):
        if isinstance(node, BlockNode) and node.name == 'context':
            meta = page.nodelist.pop(i)
            break
    page._meta = meta
    return page


def page(request, slug='index'):
    """Render the requested page if found."""
    file_name = '{}.html'.format(slug)
    page = get_page_or_404(file_name)
    context = {
        'slug': slug,
        'page': page,
    }
    if page._meta is not None:
    	meta = page._meta.render(Context())
    	extra_context = json.loads(meta)
    	context.update(extra_context)
    return render(request, 'page.html', context)

def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/index.html',
        context_instance = RequestContext(request,
        {
            'title':'Jaegun Jung, Ph. D. - Home',
            'year':datetime.now().year,
        })
    )

def figures(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/figures.html',
        context_instance = RequestContext(request,
        {
            'title':'Sample plots',
            'year':datetime.now().year,
        })
    )

def papers(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/papers.html',
        context_instance = RequestContext(request,
        {
            'title':'Papers and Presentations',
            'message':'As of 2/23/2015',
            'year':datetime.now().year,
        })
    )

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/contact.html',
        context_instance = RequestContext(request,
        {
            'title':'About Jaegun',
            'message':'He is ...',
            'year':datetime.now().year,
        })
    )
"""
def post_list(request):
    return render(request, 'app/post_list.html')
"""

post_list = ListView.as_view(model=Post)

post_detail = DetailView.as_view(model=Post)

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<div class="paragraph" style="text-align:left;">
    <ul>
        <li>LinkedIn:
            <a href="https://www.linkedin.com/in/jgjung" target="_blank">
                www.linkedin.com/in/jgjung</a>
        </li>
        <li>Github:
            <a href="https://github.com/jaegunjung" target="_blank">
                github.com/jaegunjung
            </a>
        </li>
        <li>Facebook:
            <a href="https://www.facebook.com/jaegun.jung.7" target="_blank">
                www.facebook.com/jaegun.jung.7</a>
        </li>
    </ul>
</div>
<div>
    <form enctype="multipart/form-data" action="https://formspree.io/jjg0412@gmail.com"
          method="POST" id="form-messages">
        <div id="messages-form-parent" class="wsite-form-container" style="margin-top:10px;">
            <ul class="formlist" id="messages-form-list">
                <h2 style="text-align:left;">Contact me!</h2>
                <div>
                    <div class="wsite-form-field wsite-name-field" style="margin:5px 0px 5px 0px;">
                        <label class="wsite-form-label" for="input-firstName">Name
                            <span class="form-required">*</span>
                        </label>
                        <div style="clear:both;"></div>
                        <div class="wsite-form-input-container wsite-form-left wsite-form-input-first-name">
                            <input id="input-firstName" class="wsite-form-input wsite-input" type="text"
                                   name="First Name">
                            <label class="wsite-form-sublabel" for="input-firstName">First</label>
                        </div>
                        <div class="wsite-form-input-container wsite-form-right wsite-form-input-last-name">
                            <input id="input-lastName" class="wsite-form-input wsite-input" type="text"
                                   name="Last Name">
                            <label class="wsite-form-sublabel" for="input-lastName">Last</label>
                        </div>
                        <div id="instructions-name" class="wsite-form-instructions"
                             style="display:none;"></div>
                    </div>
                    <div style="clear:both;"></div>
                </div>

                <div>
                    <div class="wsite-form-field" style="margin:5px 0px 5px 0px;">
                        <label class="wsite-form-label" for="input-email">Email
                            <span class="form-required">*</span>
                        </label>
                        <div class="wsite-form-input-container">
                            <input id="input-email"
                                   class="wsite-form-input wsite-input wsite-input-width-370px" type="text"
                                   name="Email">
                        </div>
                        <div id="instructions-email" class="wsite-form-instructions"
                             style="display:none;"></div>
                    </div>
                </div>

                <div>
                    <div class="wsite-form-field" style="margin:5px 0px 5px 0px;">
                        <label class="wsite-form-label" for="input-comment">Comment
                            <span class="form-required">*</span>
                        </label>
                        <div class="wsite-form-input-container">
                    <textarea id="input-comment" class="wsite-form-input wsite-input wsite-input-width-370px"
                              name="Comment" style="height: 200px"></textarea>
                        </div>
                        <div id="instructions-comment" class="wsite-form-instructions"
                             style="display:none;"></div>
                    </div>
                </div>
            </ul>
        </div>
        <div style="display:none; visibility:hidden;">
            <input type="text" name="wsite_subject">
        </div>
        <div style="text-align:left; margin-top:10px; margin-bottom:10px;">
            <input type="hidden" name="form_version" value="2">
            <input type="hidden" name="wsite_approved" id="wsite-approved" value="weebly">
            <input type="hidden" name="ucfid" value="messages">
            <input type="submit" style="position:absolute;top:0;left:-9999px;width:1px;height:1px">
            <button type="button" onclick="document.getElementById(&#39;form-messages&#39;).submit()">Submit</button>
        </div>
    </form>
</div>

{% endblock %}
{% block scripts %}
<script>
var STATIC_BASE = 'https://formspree.io/';


</script>
{% endblock %}

app/templates/app/figures.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/slideshow.css' %}">
<script src="{% static 'app/scripts/slideshow-jq.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}

<div id="1-slideshow" class="wslide">
    <table class="wslide-main">
        <tbody>
        <tr>
            <td>
                <div class="wslide-content disable-user-select" style="height: 600px;">
                    <div class="wslide-content-inner">
                        <div class="wslide-slides">
                            <div class="wslide-slide">
                                <div class="wslide-slide-inner1">
                                    <div class="wslide-slide-inner2" style="width: 882px; left: -441px; top: -284px;">
                                        <img src="{% static 'app/content2/scatter_orig.png' %}" style="width: 882px;">
                                    </div>
                                </div>
                            </div>
                            <div class="wslide-slide" style="display: none;">
                                <div class="wslide-slide-inner1">
                                    <div class="wslide-slide-inner2" style="width: 837px; left: -419px; top: -279px;">
                                        <img src="{% static 'app/content2/O3map_orig.png' %}" style="width: 837px;">
                                    </div>
                                </div>
                            </div>
                            <div class="wslide-slide" style="display: none;">
                                <div class="wslide-slide-inner1">
                                    <div class="wslide-slide-inner2" style="width: 750px; left: -375px; top: -280px;">
                                        <img src="{% static 'app/content2/statmap_orig.png' %}" style="width: 750px;">
                                    </div>
                                </div>
                            </div>
                            <div class="wslide-slide" style="display: none;">
                                <div class="wslide-slide-inner1">
                                    <div class="wslide-slide-inner2" style="width: 751px; left: -376px; top: -301px;">
                                        <img src="{% static 'app/content2/whisker_orig.png' %}" style="width: 751px;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="wslide-overlay-top-left disable-user-select">
                        <div class="wslide-button-wrap" style="display: none;">
                            <span class="wslide-play wslide-button disable-user-select" style="opacity: 1;">
                                <span class="wslide-button-inner">Play
                                    <span class="wslide-button-icon"></span>
                                </span>
                                <span class="wslide-button-bg"></span>
                            </span>
                        </div>
                        <div class="wslide-button-wrap" style="display: none;">
                            <span class="wslide-pause wslide-button disable-user-select"
                                  style="opacity: 0; display: none;">
                                <span class="wslide-button-inner">Pause
                                    <span class="wslide-button-icon"></span>
                                </span>
                                <span class="wslide-button-bg"></span>
                            </span>
                        </div>
                    </div>
                    <div class="wslide-overlay-top-right disable-user-select">
                        <div class="wslide-button-wrap" style="display: none;">
                            <span class="wslide-prev wslide-button disable-user-select">
                                <span class="wslide-button-inner">
                                    <span class="wslide-button-icon"></span>
                                </span>
                                <span class="wslide-button-bg"></span>
                            </span>
                        </div>&nbsp;
                        <div class="wslide-button-wrap" style="display: none;">
                            <span class="wslide-next wslide-button disable-user-select">
                                <span class="wslide-button-inner">
                                    <span class="wslide-button-icon"></span>
                                </span><span class="wslide-button-bg"></span>
                            </span>
                        </div>
                    </div>
                    <div class="wslide-overlay-left disable-user-select"></div>
                    <div class="wslide-overlay-right disable-user-select"></div>
                </div>
            </td>
        </tr>
        <tr>
            <td class="wslide-link-cell" style="width: auto;">
                <div class="wslide-links disable-user-select wslide-links-bottom wslide-thumbnail-links"
                     style="height: 75px;">
                    <div class="wslide-links-inner">
                        <table>
                            <tbody>
                            <tr>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
(function(jQuery) {
    function init() {
        wSlideshow.render({
        elementID:"1",
        nav:"thumbnails",
        navLocation:"bottom",
        captionLocation:"bottom",
        transition:"fade",
        autoplay:"0",
        speed:"5",
        aspectRatio:"auto",
        showControls:"true",
        randomStart:"false",
        images:[
            {"url":"static/app/images/scatter.png",
            "width":"333",
            "height":"214",
            "caption":"Created by MS Excel." +
            " X and Y axes are set automatically by their range by embedded macro." +
            " Here ozone measured by aircraft are compared to CAMx (regional 3D chemical transport model) outputs." +
            " The location of aircraft is calculated to the 3D model specific grids." +
            " Statistics shown are calculated by perl scripts."},
            {"url":"static/app/images/O3map.png",
            "width":"333","height":"222",
            "caption":"The 4th highest daily 8-hour O3 max predicted by CAMx." +
            " NCL is used to create this contour plots."},
            {"url":"static/app/images/statmap.png",
            "width":"333",
            "height":"248",
            "caption":"Correlation Coefficient of O3 between Model and Observation." +
            " Created with NCL (spatial map) and R (calculation of R)."},
            {"url":"static/app/images/whisker.png",
            "width":"312",
            "height":"250",
            "caption":"Box and whisker plots created using a R script." +
            " Observed and Predicted ozone are plotted."}
            ]
        })
    }
    jQuery ? jQuery(init) : document.observe('dom:loaded', init)
})(window._W && _W.jQuery)



</script>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<span style="z-index:10;position:relative;float:left;margin-top:0px;*margin-top:0px">
    {% load staticfiles %}
    <img src="{% static 'app/images/Jaegun.jpg' %}"
         style="margin-top: 5px; margin-bottom: 10px; margin-left: 0px; margin-right: 10px; border-width:1px;padding:3px;"
         alt="Picture" class="galleryImageBorder">
</span>
<div class="paragraph" style="display:block;">
    <strong>Computer Skills</strong>
    <br>
    <ul>
        <li>
            <a href="https://www.python.org/"> Python </a>
            <ul>
                <li>
                    Developing web applications with <a href="https://www.djangoproject.com/"> django</a>.
                    <a href="https://docs.python.org/2/library/unittest.html"> Unit testing framework</a>.
                </li>
                <li>
                    Data analysis using <a href="http://www.numpy.org/"> numpy</a>, <a
                        href="https://pandas.pydata.org/"> pandas</a>,
                    <a href="https://github.com/yhat/pandasql"> pandasql</a>, <a href="https://matplotlib.org/">
                    matplotlib</a>, etc.
                </li>
                <li>
                    Took <a href="https://www.coursera.org/specializations/deep-learning"> Andrew Ng's Coursera Machine
                    Learning courses</a>
                    related to neural network for deep learning with <a href="http://scikit-learn.org/stable/">
                    scikit</a> (ML Course Certificate ID:
                    <a href="https://www.coursera.org/account/accomplishments/verify/LD972MEPJ28V">LD972MEPJ28V</a>).
                </li>
            </ul>
        </li>
        <li>
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"> Javascript</a> -
            Using <a href="https://jquery.com/"> jquery</a>, identifying elements and applying class for an effect.
            Controlling orders of functions using
            <a href="https://developer.mozilla.org/en-US/docs/Glossary/Callback_function"> callback</a>.
            Experienced with <a href="https://datatables.net/"> DataTable</a> and
            <a href="http://es6-features.org/"> ES6</a>.
            <br>
        </li>
        <li>
            <a href="https://en.wikipedia.org/wiki/HTML"> HTML</a> /
            <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets">CSS</a> -
            Composed a simple HTML and modified a complex HTML with CSS.
        </li>
        <li>
            <a href="https://www.mysql.com/"> MySQL</a> - Created DB and tables and manipulate data after filtering
            using query.
            Experienced working with <a href="https://www.mysql.com/products/workbench/"> Workbench</a>.
            Using <a href="https://www.r-project.org/"> R</a> or
            <a href="https://www.perl.org/"> perl</a> scripts, populated data into DB.
        </li>
        <li>
            <a href="https://www.atlassian.com/continuous-delivery/ci-vs-ci-vs-cd"> CI/CD</a> -
            Version control via <a href="https://git-scm.com/"> git</a>.
            Continuous Integration and Continuous Development (CI/CD) with
            <a href="https://jenkins.io/"> Jenkins</a> and
            <a href="https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins">
                SonarQube</a>.
        </li>
        <li>
            <a href="https://www.r-project.org/"> R</a> - Using the
            <a href="https://www.rstudio.com/"> R studio</a>,
            be efficient in working on scripts with log console and installing libraries when needed.
            Processed statistical metrics and displayed various types of plots.
            <br>
        </li>
        <li>
            <a href="https://www.linux.org/"> Linux</a> - Skilled at using shell scripts for both
            <a href="https://en.wikipedia.org/wiki/C_shell"> csh</a> and
            <a href="https://en.wikipedia.org/wiki/Bash_(Unix_shell)"> bash</a>.
            Experienced with <a href="https://en.wikipedia.org/wiki/AWK"> awk</a>.
            Installed multiple Linux versions including
            <a href="https://www.centos.org/"> CentOS</a>,
            <a href="https://www.ubuntu.com/"> Ubuntu</a>, and
            <a href="https://getfedora.org/"> Fedora</a>.
            Diagnosed system errors checking a system log file.
        </li>
    </ul>
    <br>
    <strong>Work Experience</strong>
    <br>
    <ul>
        <li>
            December 2018 - Present &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Enovix, Freemont, CA, Sr. Principal Data Engineer
        </li>
        <li>
            March 2018 &nbsp; &nbsp; &nbsp; - November 2018 : Infosys, @Cisco, San Jose, CA, Tech. Leader
        </li>
        <li>
            March 2013 &nbsp; &nbsp; &nbsp; - March 2018 &nbsp; &nbsp; &nbsp; : Ramboll, Novato, CA, Senior Associate
        </li>
        <li>
            October 2008 &nbsp; &nbsp;- February 2013 &nbsp; : Ramboll, Novato, CA, Associate
        </li>
    </ul>
    <br>
    <strong>Education</strong>
    <br>
    <ul>
        <li>
            2008 PhD, Chemical Engineering, Carnegie Mellon University, Pittsburgh, PA
            <br>
        </li>
        <li>
            2003 BS, Chemical Engineering, Hanyang University, Seoul, Korea
        </li>
    </ul>
    <br>
    <strong>Visa Status</strong>
    <br>
    <ul>
        <li>
            Permenant Resident
            <br>
        </li>
    </ul>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html"; charset="UTF-8">
    <title>{{ title }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/sites.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/fancybox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/main_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/font_face.css' %}">
    <script src="{% static 'app/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'app/scripts/main.js' %}"></script>
    {% block extrahead %}{% endblock %}
</head>

<body class="wsite-theme-light no-header-page wsite-page-index">
<div id="header-wrap">
    <div id="page">
        <div id="header-container">
            <table id="header">
                <tbody>
                <tr>
                    <td id="logo">
                            <span class="wsite-logo">
                                <a href="/">
                                    <span id="wsite-title">Jaegun Jung, Ph. D.
                                    </span>
                                </a>
                            </span>
                    </td>
                    <td id="header-right">
                        <table>
                            <tbody>
                            <tr>
                                <td class="phone-number">
                                        <span class="wsite-text">Email jjg0412 at gmail dot com
                                        </span>
                                </td>
                                <td class="social"></td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="search"></div>
                    </td>
                </tr>
                </tbody>
            </table>
            <div id="topnav">
                <ul class="wsite-menu-default">
                    <li class="wsite-nav-0" style="position: relative;">
                        <a href="/" style="position: relative;">Home</a>
                    </li>
                    <li class="wsite-nav-0" style="position: relative;">
                        <a href="/app/" style="position: relative;">Blog</a>
                    </li>
                    <li class="wsite-nav-1" style="position: relative;">
                        <a href="/figures.html" style="position: relative;">Works done</a>
                    </li>
                    <li class="wsite-nav-2" style="position: relative;">
                        <a href="/papers.html" style="position: relative;">PUBLICATIONS &amp; PRESENTATIONS</a>
                    </li>
                    <li class="wsite-nav-3" style="position: relative;">
                        <a href="/contact.html" style="position: relative;">Personal Links</a>
                    </li>
                </ul>
                <div style="clear:both"></div>
            </div>
        </div>
    </div>
</div>
<div id="banner-wrap">
    <div id="container">
        <div class="wsite-header"></div>
    </div>
</div>
<div id="main-wrap">
    <div id="page">
        <div id="main">
            <div id="content">
                <div id="wsite-content" class="wsite-elements wsite-not-footer">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}{% endblock %}
</div>
</body>
</html>

app/templates/app/post_detail.html
{% extends "app/layout.html" %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<title>Blog</title>
<div class = "container">
    <div class="row">
        <div class="col-sm-12">
                <h1>{{ post.title }}</h1>
            </div>
            <p><img src="/{{ post.photo.url }}" /></p>
            {{ post.content|safe }}
            <hr/>
            <a href="{% url 'app:post_list' %}" class="btn btn-primary">Back to list</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/post_list.html
{% extends "app/layout.html" %}

{% block content %}
<title>Blog</title>
<div class = "container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover table-bordered">
            {% for post in post_list %}
                <tr>
                    <td>
                        <a href="{% url 'app:post_detail' post.pk %}">
                            {{ post.title }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}